language: node_js
node_js:
  - "10"
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
  - yarn lerna bootstrap
script:
  - yarn test --maxWorkers=2
after_success:
  - cat ./packages/coverage/lcov.info | ./node_modules/codacy-coverage/bin/codacy-coverage.js --token $CODACY_PROJECT_TOKEN
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
