* Doc va phan tich yeu cau
Input: 2 nodes g, h o trong binary tree
Output: node dau tien la to tien cua ca 2 node g, h

* TDD: Setup test case
Done

* Dua ra brute force solution/ y tuong
Co 3 cau hoi ta can dat ra vi no anh huong truc tiep den y tuong/solution

Cach 1. Neu nhu BinaryTree co link den parent node
Trong truong hop nay, ta can move up a 2 node den khi nao parent cua ca 2 gap nhau la xong
Steps:
1. Kiem tra do cao cua g va h
2. Move up node co do cao hon de 2 node nay cung do cao (vi ta di lan tung buoc 1)
3. Di len tang buoc 1 su dung link to parent
4. Kiem tra g.parent === h.parent khong neu co tra ve g.parent
5. Neu khong move up va loop
6. Ta dam bao se luon luon co parent cua ca 2 node chinh la root

Cach 2. BinaryTree co parent node
Ta nhan thay la, to tien dau tien chua ca g, h se o tren path cua g de den root.
Thay vi move ca 2 len, ta chi can di theo duong cua g, va tim xem cac duong la anh em cua g.parent co duong nao chua h hay khong. Neu khong ta move len cao va tim tiep
Steps:
1. Kiem tra root cover g, hay root cover h hay khong neu khong thi tra ve -1 (error)
2. Gan sibling => anh em cua g
3. Gan parent = g.parent
4. kiem tra sibling co chua h hay khong?
5. Neu chua h thi tra ve parent, neu khong lap lai
6. sibling => sibling cua parent
7. parent => tang 1 bac = parent.parent
8. Cuoi cung tra ve parent

Cach 3. Khong co node den parent
Gia su g va h deu co trong BT.Ta can tim ra dac diem thuoc tinh de tim g, h
To tien chung cua g, h de co dac diem la, g/h phai o nhanh ben trai, node con lai se phai o nhanh ben con lai.
Vi neu nhu g/h cung o tren 1 nhanh (n.left) thi n.left moi la to tien chung dau tien cua g, h.
Ta suy ra y tuong la neu nhu cover(n.left, h) && cover(n.left, g) => tim tiep trong n.left
Tuong tu cho n.right.
Neu nhu khong thi n chinh la to tien chung dau tien

Steps:
1. Kiem tra cover(root, g), cover(root, h) neu 1 trong 2 khong co trong root thi tra ve -1 (error)
2. Kiem tra node.left co chua g va h hay khong neu co de quy tiep cho root.left
3. Kiem tra node.right co chua g va h hay khong neu co de quy tiep cho root.right
4. Tra ve node

* Toi uu vao so sanh cac thuat toan

* TODO Bat dau code thuat toan thich hop nhat

* TODO Test va fix bug neu co

#+BEGIN: clocktable :scope file :maxlevel 2
#+CAPTION: Clock summary at [2018-08-07 Tue 22:10]
| Headline     | Time   |
|--------------+--------|
| *Total time* | *0:00* |
#+END:
