export const indexSource: (problem: string) => string = (
  problem: string
): string => `/**
 * THIS IS AN AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 */

export * from './${problem}';
`;

export const indexRootSource: (problems: string[]) => string = (
  problems: string[]
): string => `/**
 * THIS IS AN AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 */

${problems.map((p: string) => `export * from './${p}';`).join('\n')}
`;
